# Generated by Django 5.2.6 on 2025-09-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(default='Default Vehicle', max_length=50),
            preserve_default=False,
        ),
    ]
