# Generated by Django 5.2.6 on 2025-09-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_name',
        ),
    ]
